import os
import requests
from bs4 import BeautifulSoup

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
URL = "https://www.forebet.com/en/football-tips-and-predictions-for-tomorrow"

def get_forebet_top_picks():
    # User-Agent header is required to bypass default scraper blocks
        headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                    }
                        
                            response = requests.get(URL, headers=headers)
                                soup = BeautifulSoup(response.text, "html.parser")
                                    
                                        # Rows containing match predictions
                                            match_rows = soup.find_all("div", class_="rcnttr")
                                                top_picks = []

                                                    for row in match_rows:
                                                            try:
                                                                        # Extract Team Names
                                                                                    home_team = row.find("span", class_="homeTeam").text.strip()
                                                                                                away_team = row.find("span", class_="awayTeam").text.strip()
                                                                                                            
                                                                                                                        # Extract Win Probabilities (1 X 2)
                                                                                                                                    prob_spans = row.find("div", class_="tr_probabilities").find_all("span")
                                                                                                                                                p_home = float(prob_spans[0].text.strip())
                                                                                                                                                            p_draw = float(prob_spans[1].text.strip())
                                                                                                                                                                        p_away = float(prob_spans[2].text.strip())

                                                                                                                                                                                    # Check criteria: Either Home >= 75% or Away >= 75%
                                                                                                                                                                                                if 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                # Extract Odds / COEF
                                                                                                                                                                                                                                                                                                                                                if odds_elem:
                                                                                                                                                                                                                                                                                                                                                                    odd_text = odds_elem.text.strip().split()[0] # Grab first odds entry
                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                odds_val = float(odds_text)
                                                                                                                                                                                                                                                                                                                                                                                                                                    except ValueError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            odds_val = 0.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            top_picks.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "home": home_team,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "away": away_team,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "pick": picked_side,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "prob": highest_prob,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "coef": odds_val
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Skip rows missing necessary fields (e.g. ad banners or postponed matches)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                continue

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Sort descending by COEF (highest odds first)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        top_picks.sort(key=lambda x: x["coef"], reverse=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return top_picks

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def send_telegram_message(message):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                telegram_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Break into chunks if message exceeds Telegram limit (4096 chars)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(message) > 4000:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(0, len(message), 4000):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                payload = {"chat_id": CHAT_ID, "text": message[i:i+4000], "parse_mode": "Markdown"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            requests.post(telegram_url, json=payload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        payload = {"chat_id": CHAT_ID, "text": message, "parse_mode": "Markdown"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                requests.post(telegram_url, json=payload)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if 