name: Forebet Daily Scraper

on:
  schedule:
    - cron: '0 7 * * *' # Scheduled daily execution at 07:00 AM UTC
  workflow_dispatch:
    inputs:
      target_day:
        description: 'Select Target Page'
        required: true
        default: 'today'
        type: choice
        options:
          - today
          - tomorrow

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests playwright
          playwright install --with-deps chromium

      - name: Run Scraper Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py ${{ github.event.inputs.target_day || 'today' }}
